### ISSUE TITLE
vid hardcoded to 1 in taxonomy_get_tree() call in template.php

### ISSUE THREAD

**Issue by jpilchisu** [isubit/suitcase_interim#18]
In `elseif ($vars['region'] == 'search') {` within template.php a call to taxonomy_get_tree() is made with the vid hardcoded to 1. This could cause unexpected behavior.

**Comment by njbooher** [comment]
https://github.com/isubit/suitcase_interim/commit/6bc8393fc72ecbd700f18d13a25eb11e7f9584fe

Fixed.
